#!/bin/sh

bldwht='\e[1;37m'
txtpur='\e[0;35m' 
txtwht='\e[0;37m'
txtgrn='\e[0;32m' 

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[$bldwht\]\w\[$txtpur\]\$(parse_git_branch)\[$txtwht\] $ \[$txtgrn\]"

alias ll='ls -lah'
